### ISSUE TITLE
Otras listas

### ISSUE THREAD

**Issue by YerkoPalma** [proinchile/APIS-PUBLICAS-CHILE#1]
Estimad@s,

Existen otras listas:

- https://github.com/juanbrujo/listado-apis-publicas-en-chile
- https://github.com/YerkoPalma/npm-chile

Sería buena idea referenciar en un único sitio todas las listas disponibles.
Además, si su lista de apis esta basada en otra lista anterior (la primera), sería _conveniente_ mencionarlo.

Saludos.

**Comment by DiruzCode** [comment]
Tienes mucha razón @YerkoPalma  se agregaran ahora mismo las otras lista y de donde se obtuvo la información, gracias master.
